server:
  port: 10020
spring:
  application:
    name: imgup-service
  servlet:
    multipart:
      max-file-size: 1MB #文件上传时，单个文件，不能超过1MB
      max-request-size: 10MB #上传时，所有文件的总和，不能超过10M

##自定义属性，用于设置文件上传时的保存路径
file:
  imgup: C:\\j64file
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8762/eureka/